## Task 1: NumPy Linear Algebra

### Problem Statement
1. Create a 3x3 matrix of random integers between 1 and 20.
2. Compute the determinant of the matrix.
3. Verify if the matrix is invertible.
4. If invertible, calculate the inverse.

### Theory
The determinant of a square matrix is a scalar value that can be computed from its elements. A matrix is invertible if and only if its determinant is non-zero.

In [1]:
import numpy as np

# Step 1: Create a random 3x3 matrix
matrix = np.random.randint(1, 21, (3, 3))

# Step 2: Compute the determinant
determinant = np.linalg.det(matrix)
print("Matrix:\n", matrix)
print("Determinant:", determinant)

# Step 3: Check invertibility
if determinant != 0:
    # Step 4: Compute the inverse
    inverse = np.linalg.inv(matrix)
    print("Inverse:\n", inverse)
else:
    print("The matrix is not invertible.")

### Your Solution (Write your code here)

Matrix:
 [[10 10 12]
 [ 3 14  4]
 [12 13 20]]
Determinant: 612.0
Inverse:
 [[ 0.37254902 -0.07189542 -0.20915033]
 [-0.01960784  0.09150327 -0.00653595]
 [-0.21078431 -0.01633987  0.17973856]]


## Task 2: Pandas Data Analysis

### Problem Statement
1. Read a CSV file containing sales data.
2. Group the data by product and compute total sales for each product.
3. Find the top 3 products with the highest sales.

In [8]:
import pandas as pd

# Step 1: Read the CSV file
data = pd.read_csv('sales-data-sample.csv')

# # Step 2: Group by product and calculate total sales
# product_sales = data.groupby('Product')['Sales'].sum()

# # Step 3: Sort and find the top 3 products
# top_products = product_sales.sort_values(ascending=False).head(3)
# print("Top 3 Products:\n", top_products)

### Your Solution (Write your code here)

## Task 3: Matplotlib Data Visualization

### Problem Statement
1. Create a line plot of sales trends over time.
2. Customize the plot with appropriate labels, title, and gridlines.
3. Save the plot as an image.

In [14]:
data['ShipDate']

0       2011-01-08T00:00:00.000Z
1       2011-01-09T00:00:00.000Z
2       2011-01-09T00:00:00.000Z
3       2011-01-09T00:00:00.000Z
4       2011-01-13T00:00:00.000Z
                  ...           
9989    2015-01-04T00:00:00.000Z
9990    2015-01-04T00:00:00.000Z
9991    2015-01-04T00:00:00.000Z
9992    2015-01-04T00:00:00.000Z
9993    2015-01-04T00:00:00.000Z
Name: ShipDate, Length: 9994, dtype: object

In [15]:
import matplotlib.pyplot as plt
import pandas as pd

# Step 1: Generate data
# (Use a sample DataFrame if no CSV is available)
# data = pd.read_csv('sales-data-sample.csv')

# # Step 2: Plot sales trends
# data['Date'] = pd.to_datetime(data['Date'])
# data = data.sort_values('Date')

# plt.figure(figsize=(10, 6))
# plt.plot(data['Date'], data['Sales'], label='Sales Trend', color='blue')
# plt.xlabel('Date')
# plt.ylabel('Sales')
# plt.title('Sales Trends Over Time')
# plt.grid(True)
# plt.legend()

# # Step 3: Save the plot
# plt.savefig('sales_trends.png')
# plt.show()

## Scoring and Subject Points
### Task 1: NumPy Linear Algebra
- Matrix creation: **1 point**
- Determinant calculation: **2 points**
- Invertibility check: **1 point**
- Inverse calculation: **2 points**

### Task 2: Pandas Data Analysis
- Reading CSV: **1 point**
- Grouping and summing: **2 points**
- Sorting and finding top 3: **2 points**

### Task 3: Matplotlib Data Visualization
- Plot creation: **2 points**
- Customization (labels, grid, title): **2 points**
- Saving the plot: **1 point**
